repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-yaml
      - id: check-ast
      - id: trailing-whitespace
        exclude: "tests/functional/t/trailing_whitespaces.py"
      - id: end-of-file-fixer
        exclude: "tests/functional/m/missing/missing_final_newline.py|tests/functional/t/trailing_newlines.py"
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        exclude: &fixtures tests/functional/|tests/input|tests/extensions/data|tests/regrtest_data/|tests/data/
        args:
          - --in-place
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  #- repo: https://github.com/PyCQA/isort
  #  rev: 5.9.1
  #  hooks:
  #    - id: isort
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
  - repo: https://github.com/Pierre-Sassoulas/black-disable-checker/
    rev: 1.0.1
    hooks:
      - id: black-disable-checker
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        exclude: *fixtures
  - repo: local
    hooks:
      #- id: pylint
      #  name: pylint
      #  entry: pylint
      #  language: python
      #  types: [python]
      - id: fix-documentation
        name: Fix documentation
        entry: python3 -m script.fix_documentation
        language: system
        types: [text]
        files: ^(ChangeLog|doc/whatsnew/\d+\.\d+\.rst)
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.3.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
